name: Compile OneBot-YaYa
on:
  push:
    branches: [ master ]
  release:
    types: [created]

jobs:
  my-job:
    name: Build OneBot-YaYa 🚀
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Install mingw
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gcc-multilib
        sudo apt-get install -y gcc-mingw-w64
        sudo apt-get install -y gcc-aarch64-linux-gnu
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Cache Go
      id: cache
      uses: actions/cache@v2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}

    - name: Tidy Go modules
      run: go mod tidy
      
    - name: Build
      run: export GOOS=windows; export GOARCH=386; export CGO_ENABLED=1; export CXX=i686-w64-mingw32-g++; export CC=i686-w64-mingw32-gcc; go build -buildmode=c-shared -o artifacts/OneBot-YaYa.XQ.dll

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: OneBot-YaYa DLL
        # A file, directory or wildcard pattern that describes what to upload
        path: ./artifacts
